# Generated by Django 4.2.3 on 2023-07-18 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postidea',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_ideas', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='postidea',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_ideas', to='projects.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='postidea',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_ideas', to='projects.format', verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='postidea',
            name='heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_ideas', to='projects.heading', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='postidea',
            name='is_done',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_ideas', to='projects.done', verbose_name='Готово'),
        ),
        migrations.AlterField(
            model_name='postidea',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_ideas', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='postidea',
            name='social_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_ideas', to='projects.socialnetwork', verbose_name='Площадка'),
        ),
    ]
