# Generated by Django 4.2.3 on 2023-07-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_postidea_author_alter_postidea_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubricator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examples', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.contenttype')),
                ('heading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.heading')),
            ],
        ),
    ]
