# Generated by Django 4.2.3 on 2023-07-20 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rubricator_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rubricator',
        ),
    ]
