# Generated by Django 4.2.3 on 2023-07-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubricator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubricator',
            old_name='examples',
            new_name='description',
        ),
    ]
