# Generated by Django 4.2.3 on 2023-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubricator', '0002_rename_examples_rubricator_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricator',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
